- name: build Sufia vm 
  # provision vagrant box ready for cap deployment of https://github.com/curationexperts/newfia or similar Sufia 6.x project
  hosts: default
  remote_user: vagrant
  vars:
    ansible_become_pass: vagrant
  roles:
    - { role: vagrant_setup }
    - { role: packages, sudo: yes }
    - { role: mount_opt, data_device: /dev/sdb }
    - { role: openjdk1_8 }
    - { role: set_timezone, sudo: yes }
    - { role: system_setup, sudo: yes }
    - { role: capistrano_setup, sudo: yes }
    - { role: ruby }
    - { role: hydra-stack/install, fedora_version: '4.3.0' }
    - { role: hydra-stack/config-capistrano }
    - { role: sufia_dependencies/install }
    - { role: sufia_dependencies/config }
    - { role: apache-passenger/install, sudo: yes }
    - { role: apache-passenger/config, sudo: yes }
    - { role: app-config, sudo: yes }

