- name: provision basic vagrant box
  hosts: vagrant
  remote_user: vagrant
  vars:
    ansible_become_pass: vagrant
    capistrano_user: vagrant
    capistrano_group: vagrant
  roles:
#    - { role: whole_hydra }
    - { role: vagrant-housekeeping, sudo: yes }
    - { role: ruby }
    - { role: hydra-stack }
    - { role: services }
    - { role: passenger, sudo: yes }
    - { role: app-config, sudo: yes }
