- name: build Sufia vm 
  # provision vagrant box ready for cap deployment of https://github.com/curationexperts/newfia or similar Sufia 6.x project
  hosts: default
  remote_user: vagrant
  vars:
    ansible_become_pass: vagrant
  roles:
    - { role: vagrant_setup }
    - { role: packages }
    - { role: mount_opt, data_device: /dev/sdb }
    - { role: openjdk1_8 }
    - { role: set_timezone }
    - { role: system_setup }
    - { role: capistrano_setup }
    - { role: ruby }
    - { role: hydra-stack/install, fedora_version: '4.3.0' }
    - { role: hydra-stack/config-capistrano }
    - { role: sufia_dependencies/install, fits_version: '0.6.2' }
    - { role: sufia_dependencies/config }
    - { role: ffmpeg }
    - { role: imagemagick }
    - { role: apache-passenger/install }
    - { role: apache-passenger/config }
    - { role: app-config }
    - { role: newfia }

